server:
  tomcat:
    relaxed-query-chars: '[,]'

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        health-check-tls-skip-verify: true
        scheme: https

  application:
    name: MAIN-SERVICE

  datasource:
    username: "postgres"
    password: "Gungun124"
    url: jdbc:postgresql://localhost:8888/SOA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

