eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

zuul:
  routes:
    agency:
      path: /agency/**
      url: http://SECOND-SERVICE/

server:
  port: 8082


spring:
  application:
    name: API-GATEWAY

