eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    agency:
      path: /agency/**
      service-id: SECOND-SERVICE

server:
  port: 15000
  ssl:
    key-store: soa3.p12
    key-password: 123456
    key-store-type: PKC12


spring:
  application:
    name: API-GATEWAY

